### ISSUE TITLE
Allow ignoring of files/paths?

### ISSUE THREAD

**Issue by ahgraber** [sirosen/texthooks#1]
I have several files where smartquotes are intentionally present so the code can identify and parse them. It would be ideal to be able to ignore these files from fix-smartquotes. Is there a configuration option to allow this?

**Comment by sirosen** [comment]
How are you running the fixer?

If you're doing so via `pre-commit`, there are pre-commit configuration options to skip files or directories (look for `exclude` in the docs).

As I have to budget my time for this (and other) projects, I'd like to rely on `pre-commit`'s file selection logic as much as possible.

**Comment by ahgraber** [comment]
::facepalm:: right.  I'll do that.  Thanks for the tip.
