### ISSUE TITLE
alphabetize-codeowners does not ignore comments

### ISSUE THREAD

**Issue by thiagowfx** [sirosen/texthooks#95]
## Original

```
/environments/cloud/services/ts/services/importexport/src/migration.ts # migration order file updated by everyone
/environments/common/npm/migration-validations/ @zzz/analytics # tool for generation/validation of migrations
```

## Observed

```
/environments/cloud/services/ts/services/importexport/src/migration.ts # by everyone file migration order updated
/environments/common/npm/migration-validations/ # @zzz/analytics for generation/validation migrations of tool
```

In the first line, it's sorting the words in the comments, which is incorrect. It should leave everything after the `#` alone.

In the second line, it's producing an error: the `@zzz/analytics` team is moved to a comment.

**Comment by sirosen** [comment]
Yep! I'm torn on whether to call this a "bug" or a "feature", but the report is correct and much appreciated!

The hook doesn't expect / handle an inline comment. I'll probably tinker on this and deliver a new version for this in the next few days.

**Comment by thiagowfx** [comment]
Thank you!
